version: '3.4'

services:
  gamesanalysis:
    image: gamesanalysis
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /mnt/chromastate:/mnt/chromastate

  database:
    image: "postgres" # use latest official postgres version
    ports:
      - "5432:5432"
    env_file:
      - .env # configure postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  postgres-data: null # named volumes can be managed easier using docker-compose
